// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ReplacePartialController from "./replace_partial_controller"
application.register("replace-partial", ReplacePartialController)

import SearchNodesController from "./search_nodes_controller"
application.register("search-nodes", SearchNodesController)
