// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CheckController from "./check_controller"
application.register("check", CheckController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NodesAjaxController from "./nodes_ajax_controller"
application.register("nodes-ajax", NodesAjaxController)

import SearchChildrenController from "./search_children_controller"
application.register("search-children", SearchChildrenController)

import SearchNodesController from "./search_nodes_controller"
application.register("search-nodes", SearchNodesController)

import SearchSiblingsController from "./search_siblings_controller"
application.register("search-siblings", SearchSiblingsController)
